# Generated by Django 2.0 on 2023-08-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phno',
            new_name='phone',
        ),
    ]
